#!/usr/bin/env python3
"""ECS Discovery Agent - Step 1 of RDS to Aurora Migration.

Searches the ECS config cache (generated by dump_ecs_config.py) to find all
services that reference a given RDS endpoint — directly or via DNS CNAME aliases.

Produces a detailed report with every matched variable and secret, ready for
the migration cutover phase.

Usage:
    # First, generate the cache (once):
    python scripts/dump_ecs_config.py

    # Then search against it (instant, repeatable):
    python scripts/discover_ecs_services.py --config config/migration.yaml

    # Search a single endpoint:
    python scripts/discover_ecs_services.py --endpoint "mydb.xxx.rds.amazonaws.com" \\
        --cnames "mydb.conekta.com"

    # Refresh cache and search in one shot:
    python scripts/discover_ecs_services.py --config config/migration.yaml --refresh
"""

import argparse
import json
import subprocess
import sys
from datetime import datetime, timezone

import yaml


DEFAULT_CACHE = "output/ecs_config_cache.json"
DEFAULT_REPORT = "output/discovery_report.json"


def load_config(config_path):
    with open(config_path) as f:
        return yaml.safe_load(f)


def load_cache(cache_path):
    with open(cache_path) as f:
        return json.load(f)


def value_matches_endpoint(value, rds_endpoint, cnames):
    """Check if a value references the RDS endpoint or any of its CNAME aliases.

    Returns (matched: bool, matched_via: str | None, matched_string: str | None).
    """
    if value is None:
        return False, None, None

    if rds_endpoint in value:
        return True, "direct", rds_endpoint

    for alias in cnames:
        if alias in value:
            return True, f"cname:{alias}", alias

    return False, None, None


def search_cache(cache_data, rds_endpoint, cnames):
    """Search the cached ECS config for references to an RDS endpoint.

    Returns a list of match dicts with full detail on where the endpoint was found.
    """
    matches = []

    for cluster in cache_data.get("clusters", []):
        cluster_name = cluster["cluster_name"]

        for svc in cluster.get("services", []):
            service_name = svc["service_name"]
            task_def_arn = svc["task_definition_arn"]

            for container in svc.get("containers", []):
                container_name = container["name"]

                # Search environment variables
                for env in container.get("environment", []):
                    matched, via, matched_str = value_matches_endpoint(
                        env.get("value", ""), rds_endpoint, cnames
                    )
                    if matched:
                        matches.append({
                            "cluster": cluster_name,
                            "service": service_name,
                            "service_arn": svc["service_arn"],
                            "task_definition": task_def_arn,
                            "container": container_name,
                            "source_type": "environment_variable",
                            "variable_name": env["name"],
                            "variable_value": env["value"],
                            "matched_via": via,
                            "matched_string": matched_str,
                        })

                # Search secrets (already resolved in cache)
                for secret in container.get("secrets", []):
                    resolved = secret.get("resolved_value")
                    if resolved is None:
                        continue

                    matched, via, matched_str = value_matches_endpoint(
                        resolved, rds_endpoint, cnames
                    )
                    if matched:
                        # Extract the specific key from JSON secrets
                        secret_key_detail = None
                        try:
                            parsed = json.loads(resolved)
                            if isinstance(parsed, dict):
                                for k, v in parsed.items():
                                    if isinstance(v, str) and (
                                        rds_endpoint in v
                                        or any(a in v for a in cnames)
                                    ):
                                        secret_key_detail = {"key": k, "value": v}
                                        break
                        except (json.JSONDecodeError, TypeError):
                            pass

                        entry = {
                            "cluster": cluster_name,
                            "service": service_name,
                            "service_arn": svc["service_arn"],
                            "task_definition": task_def_arn,
                            "container": container_name,
                            "source_type": secret["source_type"],
                            "variable_name": secret["name"],
                            "valueFrom": secret["valueFrom"],
                            "matched_via": via,
                            "matched_string": matched_str,
                        }
                        if secret_key_detail:
                            entry["secret_key"] = secret_key_detail["key"]
                            entry["secret_key_value"] = secret_key_detail["value"]
                        else:
                            entry["resolved_value_preview"] = resolved[:200]

                        matches.append(entry)

    return matches


def print_report(endpoint_name, endpoint, cnames, matches):
    """Print a human-readable report for one endpoint."""
    print(f"\n{'=' * 70}")
    print(f"RDS: {endpoint_name}")
    print(f"Endpoint: {endpoint}")
    if cnames:
        print(f"CNAMEs: {', '.join(cnames)}")
    print(f"Matches: {len(matches)}")
    print("=" * 70)

    if not matches:
        print("  No services found using this endpoint.\n")
        return

    # Group by service for cleaner output
    by_service = {}
    for m in matches:
        key = f"{m['cluster']}/{m['service']}"
        by_service.setdefault(key, []).append(m)

    for svc_key, svc_matches in by_service.items():
        first = svc_matches[0]
        print(f"\n  Cluster:    {first['cluster']}")
        print(f"  Service:    {first['service']}")
        print(f"  Task Def:   {first['task_definition']}")

        for m in svc_matches:
            src = m["source_type"]
            var = m["variable_name"]
            via = m["matched_via"]

            if src == "environment_variable":
                print(f"    ENV  {var} = {m['variable_value']}")
                print(f"         matched via: {via}")
            else:
                print(f"    SECRET  {var} (from: {m['valueFrom']})")
                if "secret_key" in m:
                    print(f"            key: {m['secret_key']} = {m['secret_key_value']}")
                else:
                    print(f"            preview: {m.get('resolved_value_preview', 'N/A')}")
                print(f"            matched via: {via}")

        print(f"  {'─' * 50}")


def main():
    parser = argparse.ArgumentParser(
        description="Search ECS config cache for services using RDS endpoints."
    )
    parser.add_argument(
        "--endpoint",
        help="Single RDS endpoint to search for",
    )
    parser.add_argument(
        "--cnames", nargs="+", default=[],
        help="CNAME aliases for --endpoint",
    )
    parser.add_argument(
        "--config",
        help="Migration YAML config (searches all source_rds_endpoints)",
    )
    parser.add_argument(
        "--cache", default=DEFAULT_CACHE,
        help=f"Path to ECS config cache JSON (default: {DEFAULT_CACHE})",
    )
    parser.add_argument(
        "--output", default=DEFAULT_REPORT,
        help=f"Path to write discovery report JSON (default: {DEFAULT_REPORT})",
    )
    parser.add_argument(
        "--refresh", action="store_true",
        help="Re-run dump_ecs_config.py before searching",
    )
    parser.add_argument(
        "--profile", default="prd",
        help="AWS profile for --refresh (default: prd)",
    )
    parser.add_argument(
        "--region", default=None,
        help="AWS region for --refresh",
    )
    args = parser.parse_args()

    if not args.endpoint and not args.config:
        parser.error("Either --endpoint or --config is required")

    # Refresh cache if requested
    if args.refresh:
        print("Refreshing ECS config cache...")
        cmd = [
            sys.executable, "scripts/dump_ecs_config.py",
            "--profile", args.profile,
            "--output", args.cache,
        ]
        if args.region:
            cmd += ["--region", args.region]
        subprocess.run(cmd, check=True)
        print()

    # Load cache
    try:
        cache_data = load_cache(args.cache)
    except FileNotFoundError:
        print(f"ERROR: Cache file not found: {args.cache}", file=sys.stderr)
        print("Run 'python scripts/dump_ecs_config.py' first, or use --refresh.", file=sys.stderr)
        sys.exit(1)

    print(f"Cache loaded: {args.cache}")
    print(f"  Dumped at: {cache_data.get('dumped_at', 'unknown')}")
    print(f"  Clusters: {cache_data.get('total_clusters', '?')}, "
          f"Services: {cache_data.get('total_services', '?')}")

    # Build endpoint list
    endpoints = []
    if args.config:
        config = load_config(args.config)
        for src in config.get("source_rds_endpoints", []):
            endpoints.append({
                "endpoint": src["endpoint"],
                "name": src.get("name", src["endpoint"]),
                "cnames": src.get("cnames", []),
            })

    if args.endpoint:
        endpoints = [{
            "endpoint": args.endpoint,
            "name": args.endpoint,
            "cnames": args.cnames,
        }]

    # Search
    full_report = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "cache_file": args.cache,
        "cache_dumped_at": cache_data.get("dumped_at"),
        "endpoints": {},
    }

    grand_total = 0
    for ep in endpoints:
        endpoint = ep["endpoint"]
        name = ep["name"]
        cnames = ep["cnames"]

        matches = search_cache(cache_data, endpoint, cnames)
        print_report(name, endpoint, cnames, matches)

        full_report["endpoints"][name] = {
            "endpoint": endpoint,
            "cnames": cnames,
            "total_matches": len(matches),
            "matches": matches,
        }
        grand_total += len(matches)

    # Summary
    if len(endpoints) > 1:
        print(f"\n{'=' * 70}")
        print("SUMMARY")
        print(f"{'=' * 70}")
        for name, data in full_report["endpoints"].items():
            count = data["total_matches"]
            ep = data["endpoint"]
            print(f"  {name}: {count} match(es)  [{ep}]")
        print(f"\n  Total matches: {grand_total}")

    full_report["grand_total_matches"] = grand_total

    # Write report
    with open(args.output, "w") as f:
        json.dump(full_report, f, indent=2, default=str)
    print(f"\nDetailed report written to: {args.output}")


if __name__ == "__main__":
    main()
