#!/usr/bin/env python3
"""DMS - Create Aurora SOURCE endpoints and duplicate tasks.

Reads the discovery report generated by dms_discover.py and for each
RDS source with a DMS task:
  1. Creates a SOURCE endpoint pointing to Aurora (aurora-psql-{dbname})
  2. Duplicates each associated task using the new Aurora SOURCE, left STOPPED

Naming conventions:
  Endpoint : aurora-psql-{dbname}  (underscores → hyphens)
  Task     : {original-task}-aurora

Usage:
    # Step 1 - run discovery first (from Mac)
    python scripts/dms_discover.py --config config/migration_microservices1_1.yaml --profile data-prd

    # Step 2 - create endpoints + tasks (from Mac)
    python scripts/dms_create_aurora_sources.py \\
        --config config/migration_microservices1_1.yaml \\
        --password <svc_data_replication_password> \\
        --profile data-prd

    # Dry-run first
    python scripts/dms_create_aurora_sources.py \\
        --config config/migration_microservices1_1.yaml \\
        --password <password> \\
        --profile data-prd --dry-run
"""

import argparse
import json
import os
import sys
from datetime import datetime, timezone

import boto3
import yaml


DEFAULT_PROFILE = "data-prd"
DEFAULT_USER    = "svc_data_replication"
REGION          = "us-east-1"


def load_config(path):
    with open(path) as f:
        return yaml.safe_load(f)


def load_discovery(path):
    with open(path) as f:
        return json.load(f)


def get_dms_client(profile):
    session = boto3.Session(profile_name=profile, region_name=REGION)
    return session.client("dms")


def read_pgpass(pgpass_path, host, port, user):
    try:
        with open(os.path.expanduser(pgpass_path)) as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith("#"):
                    continue
                parts = line.split(":")
                if len(parts) < 5:
                    continue
                pg_host, pg_port, _db, pg_user = parts[0], parts[1], parts[2], parts[3]
                password = ":".join(parts[4:])
                def m(p, v): return p == "*" or p == v
                if m(pg_host, host) and m(pg_port, str(port)) and m(pg_user, user):
                    return password
    except FileNotFoundError:
        pass
    return None


def aurora_endpoint_id(dbname):
    return f"aurora-psql-{dbname.replace('_', '-')}"


def aurora_task_id(original_task_id):
    return f"{original_task_id}-aurora"


def endpoint_exists(dms, endpoint_id):
    try:
        r = dms.describe_endpoints(Filters=[{"Name": "endpoint-id", "Values": [endpoint_id]}])
        eps = r.get("Endpoints", [])
        if eps:
            return True, eps[0]["EndpointArn"]
        return False, None
    except Exception:
        return False, None


def task_exists(dms, task_id):
    try:
        r = dms.describe_replication_tasks(
            Filters=[{"Name": "replication-task-id", "Values": [task_id]}]
        )
        return len(r.get("ReplicationTasks", [])) > 0
    except Exception:
        return False


def create_aurora_endpoint(dms, ep_id, aurora_host, dbname, user, password, ssl_mode, dry_run):
    exists, arn = endpoint_exists(dms, ep_id)
    if exists:
        print(f"    endpoint {ep_id} : already exists")
        return arn

    if dry_run:
        print(f"    endpoint {ep_id} : [dry-run] would create (db={dbname})")
        return f"arn:dry-run:{ep_id}"

    r = dms.create_endpoint(
        EndpointIdentifier=ep_id,
        EndpointType="source",
        EngineName="postgres",
        SslMode=ssl_mode,
        PostgreSQLSettings={
            "ServerName":   aurora_host,
            "Port":         5432,
            "DatabaseName": dbname,
            "Username":     user,
            "Password":     password,
        },
    )
    arn = r["Endpoint"]["EndpointArn"]
    print(f"    endpoint {ep_id} : created")
    return arn


def create_aurora_task(dms, new_task_id, src_arn, task, dry_run):
    if task_exists(dms, new_task_id):
        print(f"    task {new_task_id} : already exists — skipped")
        return False

    if dry_run:
        print(f"    task {new_task_id} : [dry-run] would create (stopped)")
        return True

    dms.create_replication_task(
        ReplicationTaskIdentifier=new_task_id,
        SourceEndpointArn=src_arn,
        TargetEndpointArn=task["target_arn"],
        ReplicationInstanceArn=task["instance_arn"],
        MigrationType=task["type"],
        TableMappings=task["mappings"],
        ReplicationTaskSettings=task["settings"],
    )
    print(f"    task {new_task_id} : created (stopped)")
    return True


def main():
    parser = argparse.ArgumentParser(
        description="Create Aurora DMS SOURCE endpoints and duplicate tasks."
    )
    parser.add_argument("--config",    required=True,          help="Migration YAML config")
    parser.add_argument("--discovery", default="",             help="Discovery JSON (default: output/dms_discovery_<config>.json)")
    parser.add_argument("--profile",   default=DEFAULT_PROFILE)
    parser.add_argument("--user",      default=DEFAULT_USER,   help="PostgreSQL user for new endpoints")
    parser.add_argument("--password",  default="",             help="Password for the PostgreSQL user")
    parser.add_argument("--pgpass",    default="~/.pgpass",    help="Fallback: read password from ~/.pgpass")
    parser.add_argument("--ssl-mode",  default="require",      help="SSL mode for new endpoints (default: require)")
    parser.add_argument("--dry-run",   action="store_true")
    args = parser.parse_args()

    config_name = os.path.splitext(os.path.basename(args.config))[0]
    discovery_path = args.discovery or f"output/dms_discovery_{config_name}.json"

    if not os.path.exists(discovery_path):
        print(f"ERROR: discovery file not found: {discovery_path}", file=sys.stderr)
        print(f"  Run first: python scripts/dms_discover.py --config {args.config} --profile {args.profile}", file=sys.stderr)
        sys.exit(1)

    config    = load_config(args.config)
    discovery = load_discovery(discovery_path)
    aurora_host = discovery["aurora_host"]

    # Resolve password
    password = args.password
    if not password:
        password = read_pgpass(args.pgpass, aurora_host, 5432, args.user)
    if not password:
        print(f"ERROR: no password for {args.user}@{aurora_host}", file=sys.stderr)
        print(f"  Use --password or add an entry to ~/.pgpass", file=sys.stderr)
        sys.exit(1)

    print("DMS — Create Aurora SOURCE endpoints + duplicate tasks")
    print(f"Config      : {args.config}")
    print(f"Discovery   : {discovery_path}")
    print(f"Aurora host : {aurora_host}")
    print(f"User        : {args.user}")
    print(f"SSL mode    : {args.ssl_mode}")
    if args.dry_run:
        print("MODE        : dry-run")
    print("=" * 70)

    dms = get_dms_client(args.profile)

    endpoints_ok = tasks_created = tasks_skipped = tasks_failed = 0

    for src in discovery["sources"]:
        rds_name = src["rds_name"]
        ep_info  = src.get("dms_endpoint")
        tasks    = src.get("tasks", [])

        print(f"\n[ {rds_name} ]")

        if not ep_info:
            print(f"  No DMS endpoint found — skipping")
            continue

        dbname = ep_info.get("db", "")
        if not dbname:
            print(f"  No database name in discovery — skipping", file=sys.stderr)
            continue

        if not tasks:
            print(f"  No tasks found — skipping")
            continue

        ep_id = aurora_endpoint_id(dbname)
        print(f"  DB      : {dbname}")
        print(f"  Tasks   : {[t['id'] for t in tasks]}")

        # Create Aurora SOURCE endpoint (one per database)
        try:
            src_arn = create_aurora_endpoint(
                dms, ep_id, aurora_host, dbname,
                args.user, password, args.ssl_mode, args.dry_run
            )
            endpoints_ok += 1
        except Exception as e:
            print(f"  ERROR creating endpoint: {e}", file=sys.stderr)
            tasks_failed += len(tasks)
            continue

        # Duplicate each task
        for task in tasks:
            new_task_id = aurora_task_id(task["id"])
            try:
                created = create_aurora_task(dms, new_task_id, src_arn, task, args.dry_run)
                if created:
                    tasks_created += 1
                else:
                    tasks_skipped += 1
            except Exception as e:
                print(f"    task {new_task_id} : ERROR — {e}", file=sys.stderr)
                tasks_failed += 1

    print(f"\n{'=' * 70}")
    print(f"  Endpoints created/found : {endpoints_ok}")
    print(f"  Tasks created           : {tasks_created}")
    print(f"  Tasks skipped           : {tasks_skipped} (already existed)")
    print(f"  Tasks failed            : {tasks_failed}")

    if tasks_failed > 0:
        sys.exit(1)


if __name__ == "__main__":
    main()
