#!/usr/bin/env python3
"""PeerDB - Create CDC mirrors (flows) for each database.

For each source RDS + database in migration.yaml:
  1. Discovers all tables dynamically from pg_catalog (BASE TABLE + PARTITIONED TABLE)
  2. Creates one CDC flow pointing source peer -> target peer

Peer names are resolved from output/peerdb_peers.json (generated by peerdb_create_peers.py).

Usage:
    python scripts/peerdb_create_mirrors.py --config config/migration.yaml

    # Dry-run
    python scripts/peerdb_create_mirrors.py --config config/migration.yaml --dry-run

    # CDC only, skip initial data copy
    python scripts/peerdb_create_mirrors.py --config config/migration.yaml --no-initial-snapshot

    # Limit to specific schemas (default: all non-system schemas)
    python scripts/peerdb_create_mirrors.py --config config/migration.yaml --include-schemas public,v2,v3

Environment variables:
    PEERDB_API_URL        e.g. http://10.210.13.211:3000
    PEERDB_AUTH_HEADER    e.g. Authorization: Basic OnBlZXJkYg==
"""

import argparse
import json
import os


def _load_dotenv():
    """Load .env from project root (two levels up from this script) into os.environ."""
    env_path = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), ".env")
    if not os.path.exists(env_path):
        return
    with open(env_path) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, _, val = line.partition("=")
            os.environ.setdefault(key.strip(), val.strip())

_load_dotenv()

import subprocess
import sys
import time
from datetime import datetime, timezone

import psycopg2
import requests
import yaml


DEFAULT_USER = "svc_claude"   # used to connect and discover tables
DEFAULT_PORT = 5432
DEFAULT_DBNAME = "postgres"
SYSTEM_DATABASES = {"postgres", "template0", "template1", "rdsadmin"}
PEERS_REPORT = "output/peerdb_peers.json"
DEFAULT_OUTPUT = "output/peerdb_mirrors.json"
DEFAULT_SCHEMAS_DIR = "output/schemas"

# PeerDB flow defaults (from reference script)
FLOW_DEFAULTS = {
    "max_batch_size": 250000,
    "idle_timeout_seconds": 300,
    "snapshot_num_rows_per_partition": 250000,
    "snapshot_max_parallel_workers": 2,
    "snapshot_num_tables_in_parallel": 2,
    "resync": False,
    "initial_snapshot_only": False,
    "soft_delete_col_name": "",
    "synced_at_col_name": "",
    "disable_peerdb_columns": True,
    "system": 1,
}


def load_config(path):
    with open(path) as f:
        return yaml.safe_load(f)


def load_peers_report(path):
    with open(path) as f:
        return json.load(f)


def pg_connect(host, port, dbname, user):
    return psycopg2.connect(
        host=host, port=port, dbname=dbname, user=user,
        connect_timeout=10,
    )


def list_databases(host, port, user):
    conn = pg_connect(host, port, DEFAULT_DBNAME, user)
    conn.set_session(readonly=True, autocommit=True)
    try:
        with conn.cursor() as cur:
            cur.execute("""
                SELECT datname FROM pg_database
                WHERE datname NOT IN %s AND datistemplate = false
                ORDER BY datname
            """, (tuple(SYSTEM_DATABASES),))
            return [row[0] for row in cur.fetchall()]
    finally:
        conn.close()


def discover_tables(host, port, user, dbname,
                    include_schemas=("public",),
                    exclude_schemas=("pg_catalog", "information_schema")):
    """Discover all BASE TABLE and PARTITIONED TABLE in the given schemas."""
    conn = pg_connect(host, port, dbname, user)
    conn.set_session(readonly=True, autocommit=True)
    try:
        with conn.cursor() as cur:
            cur.execute("""
                WITH inc(nspname) AS (
                    SELECT unnest(%s::text[])
                ),
                exc(nspname) AS (
                    SELECT unnest(%s::text[])
                )
                SELECT n.nspname || '.' || c.relname AS fqtn
                FROM pg_class c
                JOIN pg_namespace n ON n.oid = c.relnamespace
                LEFT JOIN inc i ON i.nspname = n.nspname
                LEFT JOIN exc e ON e.nspname = n.nspname
                WHERE c.relkind IN ('r', 'p')
                  AND n.nspname NOT LIKE 'pg_toast%%'
                  AND n.nspname NOT LIKE 'pg_temp_%%'
                  AND e.nspname IS NULL
                  AND (
                    (SELECT count(*) FROM inc) = 0
                    OR i.nspname IS NOT NULL
                  )
                ORDER BY 1
            """, (list(include_schemas), list(exclude_schemas)))
            return [row[0] for row in cur.fetchall()]
    finally:
        conn.close()


def peerdb_session(api_url, auth_header):
    session = requests.Session()
    if ":" in auth_header:
        name, value = auth_header.split(":", 1)
        session.headers.update({name.strip(): value.strip()})
    session.headers.update({"Content-Type": "application/json"})
    session.base_url = api_url.rstrip("/")
    return session


def mirror_exists(session, flow_job_name):
    resp = session.post(
        f"{session.base_url}/api/v1/mirrors/status",
        json={"flowJobName": flow_job_name},
    )
    if resp.status_code == 404:
        return False
    if resp.status_code not in (200, 201):
        return False
    state = resp.json().get("currentFlowState", "STATUS_UNKNOWN")
    return state != "STATUS_UNKNOWN"


def wait_mirror_running(session, flow_job_name, timeout=300, interval=10):
    """Poll mirror status until STATUS_RUNNING or a terminal failure. Returns (ok, final_state)."""
    deadline = time.time() + timeout
    while time.time() < deadline:
        try:
            resp = session.post(
                f"{session.base_url}/api/v1/mirrors/status",
                json={"flowJobName": flow_job_name},
            )
            resp.raise_for_status()
            state = resp.json().get("currentFlowState", "STATUS_UNKNOWN")
            if state == "STATUS_RUNNING":
                return True, state
            if state in ("STATUS_TERMINATED", "STATUS_UNKNOWN"):
                return False, state
            print(f"      waiting to start (state={state})...")
        except Exception as e:
            print(f"      poll error: {e}")
        time.sleep(interval)
    return False, "TIMEOUT"


def wait_mirror_terminated(session, flow_job_name, timeout=180, interval=5):
    """Poll mirror status until STATUS_TERMINATED or STATUS_UNKNOWN. Returns (ok, final_state)."""
    deadline = time.time() + timeout
    while time.time() < deadline:
        try:
            resp = session.post(
                f"{session.base_url}/api/v1/mirrors/status",
                json={"flowJobName": flow_job_name},
            )
            if resp.status_code == 404:
                return True, "STATUS_UNKNOWN"
            resp.raise_for_status()
            state = resp.json().get("currentFlowState", "STATUS_UNKNOWN")
            if state in ("STATUS_TERMINATED", "STATUS_UNKNOWN"):
                return True, state
            print(f"      waiting for termination (state={state})...")
        except Exception as e:
            print(f"      poll error: {e}")
        time.sleep(interval)
    return False, "TIMEOUT"


def restore_schema(target_host, port, user, schema_file):
    """Re-apply schema dump to target.

    - If DB already exists: wipe all user schemas then replay DDL (no CREATE DATABASE).
    - If DB does not exist: replay full dump including CREATE DATABASE.

    Extensions managed by RDS/Aurora (pg_stat_statements, pg_buffercache) and
    ALTER DEFAULT PRIVILEGES are always filtered out.

    Returns (ok, message).
    """
    import tempfile

    if not os.path.exists(schema_file):
        return False, f"schema file not found: {schema_file}"

    dbname = os.path.splitext(os.path.basename(schema_file))[0]

    # Check if DB exists on target
    db_exists = False
    try:
        conn = pg_connect(target_host, int(DEFAULT_PORT), "postgres", user)
        conn.set_session(autocommit=True)
        with conn.cursor() as cur:
            cur.execute("SELECT 1 FROM pg_database WHERE datname = %s", (dbname,))
            db_exists = cur.fetchone() is not None
        conn.close()
    except Exception as e:
        return False, f"could not check target DB existence: {e}"

    # Objects owned by or named after RDS internals — skip entire DDL block
    SKIP_OWNERS    = {"rdsadmin"}
    SKIP_NAMES     = {"pg_stat_statements", "pg_buffercache", "awsdms"}

    with open(schema_file) as f:
        content = f.read()

    def filter_dump(content, skip_db_cmds=True):
        """Filter pg_dump output at the block level.

        pg_dump separates objects with comment headers of the form:
            -- Name: X; Type: Y; Schema: Z; Owner: W
        We skip entire blocks whose Owner or Name matches RDS internals.
        Single-line directives (CREATE DATABASE, ALTER DATABASE, \\connect,
        ALTER DEFAULT PRIVILEGES) are always removed.
        """
        import re

        # Split into blocks on the pg_dump object-header pattern
        block_header = re.compile(
            r"^--\n-- Name: (?P<name>[^;]+); Type: [^;]+; Schema: [^;]+; Owner: (?P<owner>\S+)\s*\n--\n",
            re.MULTILINE,
        )

        parts = block_header.split(content)
        # parts[0] = preamble, then groups: name, owner, block_body, name, owner, block_body, ...
        result = [parts[0]]
        i = 1
        while i < len(parts) - 2:
            name  = parts[i]
            owner = parts[i + 1]
            body  = parts[i + 2]
            i += 3

            skip = (
                owner in SKIP_OWNERS
                or any(p in name for p in SKIP_NAMES)
                or any(p in owner for p in SKIP_NAMES)
            )
            if not skip:
                result.append(body)

        filtered_lines = []
        for line in "".join(result).splitlines(keepends=True):
            s = line.strip().upper()
            if skip_db_cmds and (
                s.startswith("CREATE DATABASE")
                or s.startswith("ALTER DATABASE")
                or s.startswith("\\CONNECT")
                or s.startswith("\\C ")
            ):
                continue
            if s.startswith("ALTER DEFAULT PRIVILEGES"):
                continue
            filtered_lines.append(line)

        return "".join(filtered_lines)

    if db_exists:
        # Wipe all user-defined schemas inside the DB (avoids DROP DATABASE)
        try:
            conn = pg_connect(target_host, int(DEFAULT_PORT), dbname, user)
            conn.set_session(autocommit=True)
            with conn.cursor() as cur:
                cur.execute("""
                    SELECT nspname FROM pg_namespace
                    WHERE nspname NOT IN ('pg_catalog', 'information_schema')
                      AND nspname NOT LIKE 'pg_%'
                    ORDER BY nspname
                """)
                schemas = [row[0] for row in cur.fetchall()]
                for schema in schemas:
                    cur.execute(f'DROP SCHEMA IF EXISTS "{schema}" CASCADE')
                cur.execute("CREATE SCHEMA public")
            conn.close()
        except Exception as e:
            return False, f"could not wipe schemas: {e}"

        filtered   = filter_dump(content, skip_db_cmds=True)
        connect_db = dbname
    else:
        # DB doesn't exist — keep CREATE DATABASE / \connect
        filtered   = filter_dump(content, skip_db_cmds=False)
        connect_db = "postgres"

    with tempfile.NamedTemporaryFile(mode="w", suffix=".sql", delete=False) as tf:
        tf.writelines(filtered)
        tf_path = tf.name

    try:
        cmd = [
            "psql",
            "-h", target_host,
            "-p", str(DEFAULT_PORT),
            "-U", user,
            "-d", connect_db,
            "-v", "ON_ERROR_STOP=1",
            "-f", tf_path,
        ]
        result = subprocess.run(cmd, capture_output=True, text=True)
        if result.returncode != 0:
            return False, result.stderr.strip()[-500:]
    finally:
        os.unlink(tf_path)

    return True, "schema restored"


def create_mirror(session, flow_job_name, source_peer, target_peer,
                  tables, publication_name, replication_slot_name,
                  do_initial_snapshot, dry_run=False):
    """Create a CDC flow in PeerDB."""
    table_mappings = [
        {"source_table_identifier": t, "destination_table_identifier": t}
        for t in tables
    ]

    payload = {
        "connection_configs": {
            "flow_job_name": flow_job_name,
            "source_name": source_peer,
            "destination_name": target_peer,
            "table_mappings": table_mappings,
            "publication_name": publication_name,
            "replication_slot_name": replication_slot_name,
            "do_initial_snapshot": do_initial_snapshot,
            **FLOW_DEFAULTS,
        }
    }

    if dry_run:
        return True, payload

    resp = session.post(
        f"{session.base_url}/api/v1/flows/cdc/create",
        json=payload,
    )
    if resp.status_code in (200, 201):
        return True, resp.json()
    else:
        return False, f"HTTP {resp.status_code}: {resp.text[:300]}"


def main():
    parser = argparse.ArgumentParser(
        description="Create PeerDB CDC mirrors for each source database."
    )
    parser.add_argument("--config", required=True)
    parser.add_argument("--peers-report", default=PEERS_REPORT,
                        help=f"Peers report JSON (default: {PEERS_REPORT})")
    parser.add_argument("--user", default=DEFAULT_USER,
                        help="PostgreSQL user for table discovery")
    parser.add_argument("--port", type=int, default=DEFAULT_PORT)
    parser.add_argument("--include-schemas", default="",
                        help="Comma-separated schemas to include (default: all non-system schemas)")
    parser.add_argument("--exclude-schemas",
                        default="pg_catalog,information_schema,pg_toast",
                        help="Comma-separated schemas to exclude")
    parser.add_argument("--no-initial-snapshot", action="store_true",
                        help="Skip initial snapshot (CDC only, no data copy)")
    parser.add_argument("--database",
                        help="Only create mirror for this specific database")
    parser.add_argument("--api-url", default=os.environ.get("PEERDB_API_URL", ""))
    parser.add_argument("--auth-header", default=os.environ.get("PEERDB_AUTH_HEADER", ""))
    parser.add_argument("--output", default=DEFAULT_OUTPUT)
    parser.add_argument("--drop-existing", action="store_true",
                        help="Drop mirror, restore schema on target, then recreate")
    parser.add_argument("--schemas-dir", default=DEFAULT_SCHEMAS_DIR,
                        help=f"Directory with schema SQL files (default: {DEFAULT_SCHEMAS_DIR})")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    if not args.api_url:
        print("ERROR: --api-url or PEERDB_API_URL is required", file=sys.stderr)
        sys.exit(1)
    if not args.auth_header:
        print("ERROR: --auth-header or PEERDB_AUTH_HEADER is required", file=sys.stderr)
        sys.exit(1)

    include_schemas = tuple(s.strip() for s in args.include_schemas.split(",") if s.strip())  # empty = all
    exclude_schemas = tuple(s.strip() for s in args.exclude_schemas.split(",") if s.strip())

    config = load_config(args.config)
    sources = config.get("source_rds_endpoints", [])

    # Resolve target Aurora host (needed for schema restore on --drop-existing)
    aurora_clusters = config.get("target_aurora_clusters", [])
    target_host = aurora_clusters[0]["endpoint"] if aurora_clusters else None

    # Build peer lookup: (rds_source, database, kind) -> peer_name
    peers_by_db = {}
    try:
        peers_report = load_peers_report(args.peers_report)
        for p in peers_report.get("peers", []):
            key = (p["rds_source"], p["database"], p["kind"])
            peers_by_db[key] = p["peer_name"]
    except FileNotFoundError:
        print(f"ERROR: peers report not found: {args.peers_report}", file=sys.stderr)
        print("Run peerdb_create_peers.py first.", file=sys.stderr)
        sys.exit(1)

    session = peerdb_session(args.api_url, args.auth_header)

    do_snapshot = not args.no_initial_snapshot

    print(f"PeerDB CDC Mirrors")
    print(f"API: {args.api_url}")
    print(f"Initial snapshot: {do_snapshot}")
    if args.dry_run:
        print("MODE: dry-run")
    print("=" * 70)

    report = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "mirrors": [],
        "summary": {"created": 0, "skipped": 0, "failed": 0},
    }

    for src in sources:
        src_host = src["endpoint"]
        src_name = src["name"]

        print(f"\n[ {src_name} ]")

        try:
            databases = list_databases(src_host, args.port, args.user)
        except Exception as e:
            print(f"  ERROR listing databases: {e}", file=sys.stderr)
            continue

        for dbname in databases:
            if args.database and dbname != args.database:
                continue
            src_peer = peers_by_db.get((src_name, dbname, "source"))
            tgt_peer = peers_by_db.get((src_name, dbname, "target"))

            if not src_peer or not tgt_peer:
                print(f"  [{dbname}] ERROR: peer not found in report — run peerdb_create_peers.py first",
                      file=sys.stderr)
                report["summary"]["failed"] += 1
                continue

            # Naming convention from reference script
            flow_name  = f"mirror_{dbname}_001"
            pub_name   = f"aurora_pub_{dbname}_001"
            slot_name  = f"aurora_slot_{dbname}_001"

            print(f"\n  [{dbname}]")
            print(f"    Flow      : {flow_name}")
            print(f"    Source    : {src_peer}")
            print(f"    Target    : {tgt_peer}")
            print(f"    Pub/Slot  : {pub_name} / {slot_name}")

            # Fix tables without PK: set REPLICA IDENTITY FULL
            try:
                conn = pg_connect(src_host, args.port, dbname, args.user)
                conn.set_session(autocommit=True)
                with conn.cursor() as cur:
                    cur.execute("""
                        SELECT n.nspname, c.relname
                        FROM pg_class c
                        JOIN pg_namespace n ON n.oid = c.relnamespace
                        WHERE c.relkind IN ('r', 'p')
                          AND n.nspname NOT IN ('pg_catalog', 'information_schema')
                          AND c.relreplident != 'f'
                          AND NOT EXISTS (
                              SELECT 1 FROM pg_index i
                              WHERE i.indrelid = c.oid AND i.indisprimary
                          )
                        ORDER BY n.nspname, c.relname
                    """)
                    no_pk_tables = cur.fetchall()
                    if no_pk_tables:
                        print(f"    Tables without PK ({len(no_pk_tables)}): setting REPLICA IDENTITY FULL")
                        for schema, table in no_pk_tables:
                            cur.execute(f'ALTER TABLE "{schema}"."{table}" REPLICA IDENTITY FULL')
                            print(f"      -> {schema}.{table}")
                conn.close()
            except Exception as e:
                print(f"    ERROR setting REPLICA IDENTITY: {e}", file=sys.stderr)
                report["summary"]["failed"] += 1
                continue

            # Drop slot and publication on SOURCE if they already exist (stale from a previous mirror)
            try:
                conn = pg_connect(src_host, args.port, dbname, args.user)
                conn.set_session(autocommit=True)
                with conn.cursor() as cur:
                    # Drop replication slot if present
                    cur.execute(
                        "SELECT pg_drop_replication_slot(%s) "
                        "FROM pg_replication_slots WHERE slot_name = %s",
                        (slot_name, slot_name),
                    )
                    if cur.rowcount:
                        print(f"    Slot      : {slot_name} dropped (stale)")

                    # Drop publication if present
                    cur.execute("SELECT 1 FROM pg_publication WHERE pubname = %s", (pub_name,))
                    if cur.fetchone():
                        cur.execute(f'DROP PUBLICATION IF EXISTS "{pub_name}"')
                        print(f"    Publication: {pub_name} dropped (stale)")
                conn.close()
            except Exception as e:
                print(f"    WARN: could not clean up slot/publication: {e}", file=sys.stderr)

            # Create publication on SOURCE
            try:
                conn = pg_connect(src_host, args.port, dbname, args.user)
                conn.set_session(autocommit=True)
                with conn.cursor() as cur:
                    cur.execute(f'CREATE PUBLICATION "{pub_name}" FOR ALL TABLES')
                    print(f"    Publication: {pub_name} created")
                conn.close()
            except Exception as e:
                print(f"    ERROR creating publication: {e}", file=sys.stderr)
                report["summary"]["failed"] += 1
                continue

            # Discover tables
            try:
                tables = discover_tables(src_host, args.port, args.user, dbname,
                                         include_schemas, exclude_schemas)
                print(f"    Tables    : {len(tables)}")
                if not tables:
                    print(f"    WARN: no tables found — skipping", file=sys.stderr)
                    report["summary"]["skipped"] += 1
                    continue
            except Exception as e:
                print(f"    ERROR discovering tables: {e}", file=sys.stderr)
                report["summary"]["failed"] += 1
                continue

            # Check if mirror already exists
            if not args.dry_run and mirror_exists(session, flow_name):
                if args.drop_existing:
                    print(f"    Status    : exists — dropping...")
                    resp = session.post(
                        f"{session.base_url}/api/v1/mirrors/state_change",
                        json={"flowJobName": flow_name, "requestedFlowState": 6,
                              "dropMirrorStats": True, "skipDestinationDrop": False},
                    )
                    if resp.status_code not in (200, 201):
                        print(f"    ERROR dropping mirror: HTTP {resp.status_code}: {resp.text[:200]}", file=sys.stderr)
                        report["summary"]["failed"] += 1
                        continue
                    print(f"    Status    : dropped — waiting for termination...")
                    ok_term, term_state = wait_mirror_terminated(session, flow_name)
                    if not ok_term:
                        print(f"    ERROR: mirror did not terminate within timeout (state={term_state})", file=sys.stderr)
                        report["summary"]["failed"] += 1
                        continue
                    print(f"    Status    : terminated ({term_state})")
                    # Slot and publication cleanup is handled below (before create_mirror)

                    # Restore schema on target to leave it clean before re-syncing
                    if not target_host:
                        print(f"    ERROR: no target_aurora_clusters in config — cannot restore schema", file=sys.stderr)
                        report["summary"]["failed"] += 1
                        continue
                    schema_file = os.path.join(args.schemas_dir, src_name, f"{dbname}.sql")
                    print(f"    Schema    : restoring from {schema_file} ...")
                    ok_schema, msg_schema = restore_schema(target_host, args.port, args.user, schema_file)
                    if not ok_schema:
                        print(f"    ERROR restoring schema: {msg_schema}", file=sys.stderr)
                        report["summary"]["failed"] += 1
                        continue
                    print(f"    Schema    : restored — recreating mirror...")
                    do_snapshot = True  # always snapshot after a drop+restore
                else:
                    print(f"    Status    : already exists — skipped")
                    report["summary"]["skipped"] += 1
                    report["mirrors"].append({
                        "flow_job_name": flow_name, "database": dbname,
                        "source": src_peer, "target": tgt_peer,
                        "tables": len(tables), "status": "skipped",
                    })
                    continue

            # If target DB doesn't exist yet, restore schema first
            if not args.dry_run and target_host:
                try:
                    conn = pg_connect(target_host, args.port, "postgres", args.user)
                    conn.set_session(autocommit=True)
                    with conn.cursor() as cur:
                        cur.execute("SELECT 1 FROM pg_database WHERE datname = %s", (dbname,))
                        db_exists = cur.fetchone() is not None
                    conn.close()
                except Exception as e:
                    print(f"    ERROR checking target DB: {e}", file=sys.stderr)
                    report["summary"]["failed"] += 1
                    continue

                if not db_exists:
                    schema_file = os.path.join(args.schemas_dir, src_name, f"{dbname}.sql")
                    print(f"    Schema    : DB not found on Aurora — restoring from {schema_file} ...")
                    ok_schema, msg_schema = restore_schema(target_host, args.port, args.user, schema_file)
                    if not ok_schema:
                        print(f"    ERROR restoring schema: {msg_schema}", file=sys.stderr)
                        report["summary"]["failed"] += 1
                        continue
                    print(f"    Schema    : restored")

            ok, result = create_mirror(
                session, flow_name, src_peer, tgt_peer,
                tables, pub_name, slot_name,
                do_initial_snapshot=do_snapshot,
                dry_run=args.dry_run,
            )

            status = "created" if ok else "FAILED"
            if not ok:
                print(f"    Status    : {status}")
                print(f"    ERROR     : {result}", file=sys.stderr)
                report["summary"]["failed"] += 1
            else:
                print(f"    Status    : created — waiting for RUNNING...")
                ok_run, run_state = wait_mirror_running(session, flow_name)
                if ok_run:
                    print(f"    Status    : RUNNING")
                    status = "running"
                else:
                    print(f"    WARN      : mirror did not reach RUNNING (state={run_state})", file=sys.stderr)
                    status = f"created ({run_state})"
                report["summary"]["created"] += 1

            report["mirrors"].append({
                "flow_job_name": flow_name,
                "database": dbname,
                "source_rds": src_name,
                "source_peer": src_peer,
                "target_peer": tgt_peer,
                "publication": pub_name,
                "replication_slot": slot_name,
                "tables": len(tables),
                "initial_snapshot": do_snapshot,
                "status": status,
            })

    s = report["summary"]
    print(f"\n{'=' * 70}")
    print("SUMMARY")
    print(f"{'=' * 70}")
    print(f"  Created : {s['created']}")
    print(f"  Skipped : {s['skipped']} (already existed)")
    print(f"  Failed  : {s['failed']}")

    with open(args.output, "w") as f:
        json.dump(report, f, indent=2)
    print(f"\nReport written to: {args.output}")

    if s["failed"] > 0:
        sys.exit(1)


if __name__ == "__main__":
    main()
